config/routes.rb
Rails.application.routes.draw do
  resources :movies, only: [:index, :new, :create, :destroy, :show] # Agrega :show aquí
  resources :series, only: [:index, :new, :create, :destroy, :show]
  resources :documentary_films, only: [:index, :new, :create, :destroy, :show]

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/serie.rb
class Serie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  def index
    @documentary_films = DocumentaryFilm.all
  end

  def new
    @documentary_film = DocumentaryFilm.new
  end

  def create
    @documentary_film = DocumentaryFilm.new(documentary_film_params)
    if @documentary_film.save
      redirect_to documentary_films_path, notice: "Documental creado exitosamente."
    else
      render :new
    end
  end

  def destroy
    @documentary_film = DocumentaryFilm.find(params[:id])
    @documentary_film.destroy
    redirect_to documentary_films_path, notice: "Documental eliminado exitosamente."
  end

  def show
    @documentary_film = DocumentaryFilm.find(params[:id])
  end

  private

  def documentary_film_params
    params.require(:documentary_film).permit(:name, :synopsis, :director)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.all
    @series = Serie.all
    @documentary_films = DocumentaryFilm.all
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "Película creada exitosamente"
    else
      render :new
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path, notice: "Película eliminada exitosamente."
  end

  def show
    @movie = Movie.find(params[:id])
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Serie.all
  end

  def new
    @serie = Serie.new
  end

  def create
    @serie = Serie.new(serie_params)
    if @serie.save
      redirect_to series_path, notice: "Serie creada exitosamente."
    else
      render :new
    end
  end

  def destroy
    @serie = Serie.find(params[:id])
    @serie.destroy
    redirect_to series_path, notice: "Serie eliminada exitosamente."
  end

  def show
    @serie = Serie.find(params[:id])
  end

  private

  def serie_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/create.html.erb
<h1>DocumentaryFilms#create</h1>
<p>Find me in app/views/documentary_films/create.html.erb</p>

app/views/documentary_films/index.html.erb
<h1>Lista de Documentales</h1>

<div class="container">
  <!-- Contenedor para los botones -->
  <div class="button-row">
    <%= link_to 'Nuevo Documental', new_documentary_film_path, class: "button left-button" %>
    <%= link_to 'Volver al inicio', root_path, class: "button right-button" %>
  </div>

  <!-- Lista de documentales -->
  <ul>
    <% @documentary_films.each do |documentary_film| %>
      <li>
        <strong><%= documentary_film.name %></strong> - <%= documentary_film.director %><br>
        <p><%= documentary_film.synopsis %></p>
        <%= link_to 'Eliminar', documentary_film_path(documentary_film), method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar este documental?' }, class: "delete-button" %>
      </li>
    <% end %>
  </ul>
</div>

<footer>
  <p>Desarrollado por Patricio Hevia Fuentes - 2024</p>
</footer>

app/views/documentary_films/new.html.erb
<h1>Agregar Nuevo Documental</h1>

<%= form_with model: @documentary_film, local: true do |form| %>
  <div>
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :synopsis, "Sinopsis" %>
    <%= form.text_area :synopsis %>
  </div>

  <div>
    <%= form.label :director, "Director" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.submit "Guardar Documental" %>
  </div>
<% end %>

<%= link_to 'Volver a la lista', documentary_films_path %>

app/views/documentary_films/show.html.erb
<h1><%= @documentary_film.name %></h1>
<p><strong>Director:</strong> <%= @documentary_film.director %></p>
<p><strong>Sinopsis:</strong> <%= @documentary_film.synopsis %></p>

<%= link_to 'Volver a la lista de documentales', documentary_films_path %>
<%= link_to 'Eliminar documental', documentary_film_path(@documentary_film), method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar este documental?' } %>

app/views/home/index.html.erb
<h1>Bienvenido a la Biblioteca de Medios</h1>

<div class="container">
  <h2>Películas</h2>
  <%= link_to 'Añadir Nueva Película', new_movie_path, class: "button" %>
  <ul>
    <% @movies.each do |movie| %>
      <li>
        <strong><%= movie.name %></strong> - <%= movie.director %><br>
        <p><%= movie.synopsis %></p>
        <%= link_to 'Ver más', movie_path(movie), class: "button" %>
      </li>
    <% end %>
  </ul>

  <h2>Series</h2>
  <%= link_to 'Añadir Nueva Serie', new_serie_path, class: "button" %>
  <ul>
    <% @series.each do |serie| %>
      <li>
        <strong><%= serie.name %></strong> - <%= serie.director %><br>
        <p><%= serie.synopsis %></p>
        <%= link_to 'Ver más', serie_path(serie), class: "button" %>
      </li>
    <% end %>
  </ul>

  <h2>Documentales</h2>
  <%= link_to 'Añadir Nuevo Documental', new_documentary_film_path, class: "button" %>
  <ul>
    <% @documentary_films.each do |documentary_film| %>
      <li>
        <strong><%= documentary_film.name %></strong> - <%= documentary_film.director %><br>
        <p><%= documentary_film.synopsis %></p>
        <%= link_to 'Ver más', documentary_film_path(documentary_film), class: "button" %>
      </li>
    <% end %>
  </ul>
</div>

<footer>
  <p>Desarrollado por Patricio Hevia Fuentes - 2024</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Media App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= stylesheet_link_tag "custom", media: "all" %>


    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>

    <!-- Cargar JavaScript al final del cuerpo -->
    <%= javascript_importmap_tags %>
  </body>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/index.html.erb
<h1>Lista de Películas</h1>

<div class="container">
  <!-- Contenedor para los botones -->
  <div class="button-row">
    <%= link_to 'Nueva Película', new_movie_path, class: "button left-button" %>
    <%= link_to 'Volver al inicio', root_path, class: "button right-button" %>
  </div>

  <!-- Lista de películas -->
  <ul>
    <% @movies.each do |movie| %>
      <li>
        <strong><%= movie.name %></strong> - <%= movie.director %><br>
        <p><%= movie.synopsis %></p>
        <%= link_to 'Eliminar', movie_path(movie), method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar esta película?' }, class: "delete-button" %>
      </li>
    <% end %>
  </ul>
</div>

<footer>
  <p>Desarrollado por Patricio Hevia Fuentes - 2024</p>
</footer>

app/views/movies/new.html.erb
<h1>Agregar Nueva Película</h1>

<%= form_with model: @movie, local: true do |form| %>
  <div>
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :synopsis, "Sinopsis" %>
    <%= form.text_area :synopsis %>
  </div>

  <div>
    <%= form.label :director, "Director" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.submit "Guardar Película" %>
  </div>
<% end %>

<%= link_to 'Volver a la lista', movies_path %>

app/views/movies/show.html.erb
<h1><%= @movie.name %></h1>
<p><strong>Director:</strong> <%= @movie.director %></p>
<p><strong>Sinopsis:</strong> <%= @movie.synopsis %></p>

<%= link_to 'Volver a la lista de películas', movies_path %>
<%= link_to 'Eliminar película', movie_path(@movie), method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar esta película?' } %>

app/views/series/create.html.erb
<h1>Series#create</h1>
<p>Find me in app/views/series/create.html.erb</p>

app/views/series/index.html.erb
<h1>Lista de Series</h1>

<div class="container">
  <!-- Contenedor para los botones -->
  <div class="button-row">
    <%= link_to 'Nueva Serie', new_serie_path, class: "button left-button" %>
    <%= link_to 'Volver al inicio', root_path, class: "button right-button" %>
  </div>

  <!-- Lista de series -->
  <ul>
    <% @series.each do |serie| %>
      <li>
        <strong><%= serie.name %></strong> - <%= serie.director %><br>
        <p><%= serie.synopsis %></p>
        <%= link_to 'Eliminar', serie_path(serie), method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar esta serie?' }, class: "delete-button" %>
      </li>
    <% end %>
  </ul>
</div>

<footer>
  <p>Desarrollado por Patricio Hevia Fuentes - 2024</p>
</footer>

app/views/series/new.html.erb
<h1>Añadir Nueva Serie</h1>

<div class="container">
  <!-- Contenedor para los botones -->
  <div class="button-row">
    <%= link_to 'Volver al inicio', root_path, class: "button left-button" %>
    <%= link_to 'Lista de Series', series_path, class: "button right-button" %>
  </div>

  <!-- Formulario para añadir nueva serie -->
  <%= form_with model: @serie, local: true do |form| %>
    <% if @serie.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@serie.errors.count, "error") %> impidieron guardar la serie:</h2>
        <ul>
          <% @serie.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, "Nombre de la Serie" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :synopsis, "Sinopsis" %>
      <%= form.text_area :synopsis %>
    </div>

    <div>
      <%= form.label :director, "Director" %>
      <%= form.text_field :director %>
    </div>

    <div>
      <%= form.submit "Guardar Serie", class: "button" %>
    </div>
  <% end %>
</div>

<footer>
  <p>Desarrollado por Patricio Hevia Fuentes - 2024</p>
</footer>

app/views/series/show.html.erb
<h1><%= @serie.name %></h1>
<p><strong>Director:</strong> <%= @serie.director %></p>
<p><strong>Sinopsis:</strong> <%= @serie.synopsis %></p>

<%= link_to 'Volver a la lista de series', series_path %>
<%= link_to 'Eliminar serie', serie_path(@serie), method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar esta serie?' } %>